In [1]:
import pandas as pd

In [27]:
url = "https://raw.githubusercontent.com/Ilumiles/Pizza_Place_Sales/main/pizza_sales/order_details.csv"

order_details = pd.read_csv(url)
order_details.sample(5)

       order_details_id  order_id       pizza_id  quantity
23511             23512     10338  ckn_alfredo_m         1
44365             44366     19502     cali_ckn_l         1
2722               2723      1206     sicilian_l         1
15789             15790      6932   spicy_ital_m         1
10530             10531      4616  spinach_fet_l         1

In [3]:
order =pd.read_csv(r"C:\Users\aoilu\Documents\Data Science Techcrush\Pizza+Place+Sales\pizza_sales\orders.csv")

order.head(5)

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30

In [4]:
pizza_types =pd.read_csv(r"C:\Users\aoilu\Documents\Data Science Techcrush\Pizza+Place+Sales\pizza_sales\pizza_types.csv", encoding="cp1252")

pizza_types.head(5)

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."

In [5]:
pizza =pd.read_csv(r"C:\Users\aoilu\Documents\Data Science Techcrush\Pizza+Place+Sales\pizza_sales\pizzas.csv")

pizza.head(5)

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [6]:
#merge data

In [7]:
df1 = pd.merge(order, order_details, on = 'order_id', how = 'outer') #merging the order and order-pizaa folder together

df1.tail(5)

,order_id,date,time,order_details_id,pizza_id,quantity
48615,21348,2015-12-31,21:23:10,48616,ckn_alfredo_m,1
48616,21348,2015-12-31,21:23:10,48617,four_cheese_l,1
48617,21348,2015-12-31,21:23:10,48618,napolitana_s,1
48618,21349,2015-12-31,22:09:54,48619,mexicana_l,1
48619,21350,2015-12-31,23:02:05,48620,bbq_ckn_s,1

In [8]:
df2 = pd.merge(pizza_types, pizza, on = 'pizza_type_id', how = 'outer')

df2.tail(5)

,pizza_type_id,name,category,ingredients,pizza_id,size,price
91,the_greek,The Greek Pizza,Classic,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",the_greek_xl,XL,25.50
92,the_greek,The Greek Pizza,Classic,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",the_greek_xxl,XXL,35.95
93,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",veggie_veg_s,S,12.00
94,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",veggie_veg_m,M,16.00
95,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",veggie_veg_l,L,20.25

In [9]:
df = pd.merge(df1, df2, on="pizza_id", how ="outer")


df.head(5)

,order_id,date,time,order_details_id,pizza_id,quantity,pizza_type_id,name,category,ingredients,size,price
0,11.0,2015-01-01,13:02:59,26.0,bbq_ckn_l,1.0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",L,20.75
1,17.0,2015-01-01,13:53:00,43.0,bbq_ckn_l,1.0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",L,20.75
2,27.0,2015-01-01,15:11:17,71.0,bbq_ckn_l,1.0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",L,20.75
3,33.0,2015-01-01,15:54:08,83.0,bbq_ckn_l,1.0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",L,20.75
4,51.0,2015-01-01,18:48:28,123.0,bbq_ckn_l,1.0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",L,20.75

In [10]:
df.shape

(48625, 12)

In [11]:
df.tail(5)

,order_id,date,time,order_details_id,pizza_id,quantity,pizza_type_id,name,category,ingredients,size,price
48620,21251.0,2015-12-30,12:45:20,48406.0,veggie_veg_s,2.0,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",S,12.0
48621,21296.0,2015-12-31,15:13:40,48493.0,veggie_veg_s,1.0,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",S,12.0
48622,21298.0,2015-12-31,15:35:37,48500.0,veggie_veg_s,1.0,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",S,12.0
48623,21299.0,2015-12-31,15:52:16,48503.0,veggie_veg_s,1.0,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",S,12.0
48624,21319.0,2015-12-31,18:07:19,48553.0,veggie_veg_s,1.0,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",S,12.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48625 entries, 0 to 48624
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48620 non-null  float64
 1   date              48620 non-null  object
 2   time              48620 non-null  object
 3   order_details_id  48620 non-null  float64
 4   pizza_id          48625 non-null  object
 5   quantity          48620 non-null  float64
 6   pizza_type_id     48625 non-null  object
 7   name              48625 non-null  object
 8   category          48625 non-null  object
 9   ingredients       48625 non-null  object
 10  size              48625 non-null  object
 11  price             48625 non-null  float64
dtypes: float64(4), object(8)
memory usage: 4.5+ MB

In [14]:
df.isna().sum()

order_id            5
date                5
time                5
order_details_id    5
pizza_id            0
quantity            5
pizza_type_id       0
name                0
category            0
ingredients         0
size                0
price               0
dtype: int64

In [15]:
df[df["order_id"].isna()]

,order_id,date,time,order_details_id,pizza_id,quantity,pizza_type_id,name,category,ingredients,size,price
2372,NaN,NaN,NaN,NaN,big_meat_l,NaN,big_meat,The Big Meat Pizza,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",L,20.50
2373,NaN,NaN,NaN,NaN,big_meat_m,NaN,big_meat,The Big Meat Pizza,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",M,16.00
13610,NaN,NaN,NaN,NaN,five_cheese_m,NaN,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",M,15.50
13611,NaN,NaN,NaN,NaN,five_cheese_s,NaN,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",S,12.50
15462,NaN,NaN,NaN,NaN,four_cheese_s,NaN,four_cheese,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",S,11.75

In [16]:
#since the number of rows in few (5), its better to delete them, order id, order_details_id are missing

In [17]:
df = df.dropna(subset=["order_id"])

In [19]:
df.isna().sum()

order_id            0
date                0
time                0
order_details_id    0
pizza_id            0
quantity            0
pizza_type_id       0
name                0
category            0
ingredients         0
size                0
price               0
dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48620 entries, 0 to 48624
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48620 non-null  float64
 1   date              48620 non-null  object
 2   time              48620 non-null  object
 3   order_details_id  48620 non-null  float64
 4   pizza_id          48620 non-null  object
 5   quantity          48620 non-null  float64
 6   pizza_type_id     48620 non-null  object
 7   name              48620 non-null  object
 8   category          48620 non-null  object
 9   ingredients       48620 non-null  object
 10  size              48620 non-null  object
 11  price             48620 non-null  float64
dtypes: float64(4), object(8)
memory usage: 4.8+ MB

In [29]:
df.sample(5)

,order_id,date,time,order_details_id,pizza_id,quantity,pizza_type_id,name,category,ingredients,size,price
27185,16620.0,2015-10-08,12:23:25,37644.0,pep_msh_pep_l,1.0,pep_msh_pep,"The Pepperoni, Mushroom, and Peppers Pizza",Classic,"Pepperoni, Mushrooms, Green Peppers",L,17.50
12965,11026.0,2015-07-04,13:38:48,25061.0,five_cheese_l,1.0,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",L,18.50
24481,12807.0,2015-08-02,12:44:49,29020.0,mexicana_l,1.0,mexicana,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",L,20.25
8393,9591.0,2015-06-10,13:56:58,21855.0,ckn_alfredo_m,1.0,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",M,16.75
13816,3503.0,2015-02-28,18:15:31,7976.0,four_cheese_l,1.0,four_cheese,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",L,17.95

### 1.What is the total revenue/sales?

In [33]:
# the summation and total of price

total_revenue = df["price"].sum()
print("The total reveue/sales is $", total_revenue)

the total reveue/sales is $ 801944.7

## 2. What is the total quantity sold

In [37]:
total_quantity = df["quantity"].sum()
print("The total quantity sold: ",total_quantity)

The total quantity sold:  49574.0

## 3. Find the total order

In [38]:
total_orders = df["order_id"].nunique()
print("Total orders:", total_orders)

Total orders: 21350